<a href="https://colab.research.google.com/github/sinchana-km/pandas/blob/main/pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

In [14]:
s = pd.Series([20,30,40,50,60])

In [16]:
s.dtype

dtype('int64')

In [17]:
s.name = 'number'

In [18]:
s[2:4]

2    40
3    50
Name: number, dtype: int64

In [20]:
#iloc -> location based indexing
s.iloc[3]

np.int64(50)

In [21]:
s.iloc[[1,2,3,4]]

1    30
2    40
3    50
4    60
Name: number, dtype: int64

In [27]:
index = ["Apple","Banana","Orange","Grapes"]

In [55]:
s.index = index
s

ValueError: Length mismatch: Expected axis has 5 elements, new values have 4 elements

In [35]:
s[Apple]

NameError: name 'Apple' is not defined

In [40]:
fruit_protein = {
    "avacado":2.0,
    "goa":2.6,
    "blackbarries":2.0,
    "orange":0.9,
    "apple":0.3,
    "kiwi":1.1,
    "pomogranate":1.7,
    "mango":1.7,
    "charries":2.0
}

In [44]:
s2 = pd.Series(fruit_protein, name = "protien")
s2

avacado         2.0
goa             2.6
blackbarries    2.0
orange          0.9
apple           0.3
kiwi            1.1
pomogranate     1.7
mango           1.7
charries        2.0
Name: protien, dtype: float64

In [45]:
#conditional selection
s2[s2>1]

avacado         2.0
goa             2.6
blackbarries    2.0
kiwi            1.1
pomogranate     1.7
mango           1.7
charries        2.0
Name: protien, dtype: float64

In [49]:
#logical operation and or and not
s2[(s2 > 0.5) & (s2 <= 2.0)]

avacado         2.0
blackbarries    2.0
orange          0.9
kiwi            1.1
pomogranate     1.7
mango           1.7
charries        2.0
Name: protien, dtype: float64

In [66]:
s2["mango"] = 2.8

In [67]:
import numpy as np

In [68]:
ser = pd.Series(["a", np.nan,2])
s.notnull().sum()

np.int64(5)

In [51]:
s2

avacado         2.0
goa             2.6
blackbarries    2.0
orange          0.9
apple           0.3
kiwi            1.1
pomogranate     1.7
mango           2.8
charries        2.0
Name: protien, dtype: float64

In [71]:
employees= {
    "name": ["Amit", "Priya", "Rahul", "Sneha", "Vikram", "Anjali", "Karan", "Neha", "Suresh", "Divya"],
    "age": [24, 27, 30, 22, 35, 28, 31, 26, 29, 23],
    "department": ["Analytics", "HR", "Finance", "Analytics", "IT", "Marketing", "Finance", "Analytics", "IT", "HR"],
    "salary": [500000, 650000, 800000, 480000, 950000, 620000, 750000, 550000, 900000, 470000]
}

In [72]:
employees

{'name': ['Amit',
  'Priya',
  'Rahul',
  'Sneha',
  'Vikram',
  'Anjali',
  'Karan',
  'Neha',
  'Suresh',
  'Divya'],
 'age': [24, 27, 30, 22, 35, 28, 31, 26, 29, 23],
 'department': ['Analytics',
  'HR',
  'Finance',
  'Analytics',
  'IT',
  'Marketing',
  'Finance',
  'Analytics',
  'IT',
  'HR'],
 'salary': [500000,
  650000,
  800000,
  480000,
  950000,
  620000,
  750000,
  550000,
  900000,
  470000]}

In [74]:
def = pd.DataFrame(employees)

SyntaxError: invalid syntax (3192791565.py, line 1)

In [75]:
import pandas as pd

data_a = {
    "name": ["Amit", "Priya", "Rahul", "Sneha", "Vikram", "Anjali", "Karan", "Neha", "Suresh", "Divya"],
    "age": [24, 27, 30, 22, 35, 28, 31, 26, 29, 23],
    "department": ["Analytics", "HR", "Finance", "Analytics", "IT", "Marketing", "Finance", "Analytics", "IT", "HR"],
    "salary": [500000, 650000, 800000, 480000, 950000, 620000, 750000, 550000, 900000, 470000]
}

df = pd.DataFrame(data_a)

print(df)

     name  age department  salary
0    Amit   24  Analytics  500000
1   Priya   27         HR  650000
2   Rahul   30    Finance  800000
3   Sneha   22  Analytics  480000
4  Vikram   35         IT  950000
5  Anjali   28  Marketing  620000
6   Karan   31    Finance  750000
7    Neha   26  Analytics  550000
8  Suresh   29         IT  900000
9   Divya   23         HR  470000

In [76]:
df.iloc[2:6]

     name  age department  salary
2   Rahul   30    Finance  800000
3   Sneha   22  Analytics  480000
4  Vikram   35         IT  950000
5  Anjali   28  Marketing  620000

In [78]:
df.iloc[1:3, :4]

    name  age department  salary
1  Priya   27         HR  650000
2  Rahul   30    Finance  800000

In [79]:
df.loc[1:2,["age","department"]]

   age department
1   27         HR
2   30    Finance

In [80]:
df["age"]

0    24
1    27
2    30
3    22
4    35
5    28
6    31
7    26
8    29
9    23
Name: age, dtype: int64

In [86]:
df.drop("age", axis=1)

KeyError: "['age'] not found in axis"

In [87]:
df

     name department  salary
0    Amit  Analytics  500000
1   Priya         HR  650000
2   Rahul    Finance  800000
3   Sneha  Analytics  480000
4  Vikram         IT  950000
5  Anjali  Marketing  620000
6   Karan    Finance  750000
7    Neha  Analytics  550000
8  Suresh         IT  900000
9   Divya         HR  470000

In [84]:
df.shape

(10, 3)

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        10 non-null     object
 1   department  10 non-null     object
 2   salary      10 non-null     int64
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes

In [88]:
df.describe()

              salary
count      10.000000
mean   667000.000000
std    175375.787002
min    470000.000000
25%    512500.000000
50%    635000.000000
75%    787500.000000
max    950000.000000

In [89]:
#broadcasting

df["salary"] = df["salary"] + 5000

In [90]:
df["salary"]

0    505000
1    655000
2    805000
3    485000
4    955000
5    625000
6    755000
7    555000
8    905000
9    475000
Name: salary, dtype: int64

In [91]:
#rename colums

df.rename(columns={"department":"dept"},inplace=True)

In [93]:
df

     name       dept  salary
0    Amit  Analytics  505000
1   Priya         HR  655000
2   Rahul    Finance  805000
3   Sneha  Analytics  485000
4  Vikram         IT  955000
5  Anjali  Marketing  625000
6   Karan    Finance  755000
7    Neha  Analytics  555000
8  Suresh         IT  905000
9   Divya         HR  475000

In [94]:
df["dept"].unique()

array(['Analytics', 'HR', 'Finance', 'IT', 'Marketing'], dtype=object)

In [96]:
df["dept"].value_counts()

dept
Analytics    3
HR           2
Finance      2
IT           2
Marketing    1
Name: count, dtype: int64

In [97]:
df["promoted salary"] = df["salary"] * 10

In [98]:
df

     name       dept  salary  promoted salary
0    Amit  Analytics  505000          5050000
1   Priya         HR  655000          6550000
2   Rahul    Finance  805000          8050000
3   Sneha  Analytics  485000          4850000
4  Vikram         IT  955000          9550000
5  Anjali  Marketing  625000          6250000
6   Karan    Finance  755000          7550000
7    Neha  Analytics  555000          5550000
8  Suresh         IT  905000          9050000
9   Divya         HR  475000          4750000

In [99]:
#datacleaning
df.isnull().sum()

name               0
dept               0
salary             0
promoted salary    0
dtype: int64

if null value is there to delet that all null values use df.dropna()

df.fillna(0) it will fill all the null values with 0

df["salary"].fillna(df["Salary"].median()) # this will fill the salary missing values with median of all the salary

df["age"].fillna(method = "ffill") #this will fill the previous value with the missing value

df["age"].fillna(method = "bfill") # this will fill the next value with the missing values

In [100]:
df

     name       dept  salary  promoted salary
0    Amit  Analytics  505000          5050000
1   Priya         HR  655000          6550000
2   Rahul    Finance  805000          8050000
3   Sneha  Analytics  485000          4850000
4  Vikram         IT  955000          9550000
5  Anjali  Marketing  625000          6250000
6   Karan    Finance  755000          7550000
7    Neha  Analytics  555000          5550000
8  Suresh         IT  905000          9050000
9   Divya         HR  475000          4750000

In [103]:
df["name"]= df["name"].replace("Neha","monisha",)

In [104]:
df

      name       dept  salary  promoted salary
0     Amit  Analytics  505000          5050000
1    Priya         HR  655000          6550000
2    Rahul    Finance  805000          8050000
3    Sneha  Analytics  485000          4850000
4   Vikram         IT  955000          9550000
5   Anjali  Marketing  625000          6250000
6    Karan    Finance  755000          7550000
7  monisha  Analytics  555000          5550000
8   Suresh         IT  905000          9050000
9    Divya         HR  475000          4750000

df_dup = df[df.duplicated() # this will shows the repeated values                                                

df_dup = df[df.duplicated(keep="last") # this will keep last duplicate and shows first duplicant values

In [107]:
#invalid values:
#Lambda -> python

df["promoted salary"] = df["promoted salary"].apply(lambda x: x/10 if x >650000 else x)

In [108]:
df

      name       dept  salary  promoted salary
0     Amit  Analytics  505000         505000.0
1    Priya         HR  655000         655000.0
2    Rahul    Finance  805000         805000.0
3    Sneha  Analytics  485000         485000.0
4   Vikram         IT  955000         955000.0
5   Anjali  Marketing  625000         625000.0
6    Karan    Finance  755000         755000.0
7  monisha  Analytics  555000         555000.0
8   Suresh         IT  905000         905000.0
9    Divya         HR  475000         475000.0

In [ ]:
name = "sinchana_KM"
df[["first_name","last_name"]] = df["name"].str.split("_") #if person has first name and second name this will make seperate column for each

In [112]:
#apply and lambda
def multiplication_age(x):
  return x*2
df["age"] = df["age"].apply(multiplication_age)

In [113]:
df

      name       dept   salary  promoted salary
0     Amit  Analytics  1010000         505000.0
1    Priya         HR  1310000         655000.0
2    Rahul    Finance  1610000         805000.0
3    Sneha  Analytics   970000         485000.0
4   Vikram         IT  1910000         955000.0
5   Anjali  Marketing  1250000         625000.0
6    Karan    Finance  1510000         755000.0
7  monisha  Analytics  1110000         555000.0
8   Suresh         IT  1810000         905000.0
9    Divya         HR   950000         475000.0

In [ ]:
df["age"] = df["age"].apply(lambda x:x/2) # this will back to normal age

join -> left, right, inner, outer